---
- name: add rethinkdb repo
  apt_repository: repo="deb http://download.rethinkdb.com/apt {{ansible_lsb.codename}} main" state=present
  register: apt_repo

- name: add rethinkdb apt gpg key
  apt_key: url="http://download.rethinkdb.com/apt/pubkey.gpg"
  register: apt_gpg

- name: update apt
  apt: update_cache=yes cache_valid_time=3600
  when: apt_gpg | changed or apt_repo | changed

- name: install rethinkdb
  apt: pkg=rethinkdb state=present force=yes

- name: create rethinkdb log directory
  file: name={{rethinkdb_log}} state=directory group={{rethinkdb_group}} owner={{rethinkdb_user}}

- name: create rethinkdb data directory
  file: name={{rethinkdb_directory}} state=directory group={{rethinkdb_group}} owner={{rethinkdb_user}}

- name: check if rethinkdb data directory exists
  stat: path="{{rethinkdb_directory}}/{{inventory_hostname}}"
  register: rethinkdb_directory_exists

- name: create rethinkdb data
  command: rethinkdb create --runuser {{rethinkdb_user}} --rungroup {{rethinkdb_group}} -d {{rethinkdb_directory}}/{{inventory_hostname}}
  when: not rethinkdb_directory_exists.stat

- name: create rethinkdb configuration file
  template: src=rethinkdb.conf.j2
            dest=/etc/rethinkdb/instances.d/{{inventory_hostname}}.conf
            owner=root
            group=root
            mode=0644
  notify: restart rethinkdb
